# Generated by Django 6.0.7 on 2026-07-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_generate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Choices'},
        ),
        migrations.AlterModelOptions(
            name='passage',
            options={'verbose_name': 'Passage', 'verbose_name_plural': 'Passages'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.AddField(
            model_name='passage',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='test',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='title',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=220),
        ),
    ]
